/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: arcal_payload.idl
  Source: arcal_payload.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_ARCAL_PAYLOAD_HPP
#define DDSCXX_ARCAL_PAYLOAD_HPP

#include <cstdint>
#include <vector>

namespace arcal_dds
{
class OpaquePayload
{
private:
 std::vector<uint8_t> data_;

public:
  OpaquePayload() = default;

  explicit OpaquePayload(
    const std::vector<uint8_t>& data) :
    data_(data) { }

  const std::vector<uint8_t>& data() const { return this->data_; }
  std::vector<uint8_t>& data() { return this->data_; }
  void data(const std::vector<uint8_t>& _val_) { this->data_ = _val_; }
  void data(std::vector<uint8_t>&& _val_) { this->data_ = _val_; }

  bool operator==(const OpaquePayload& _other) const
  {
    (void) _other;
    return data_ == _other.data_;
  }

  bool operator!=(const OpaquePayload& _other) const
  {
    return !(*this == _other);
  }

};

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::arcal_dds::OpaquePayload>::getTypeName()
{
  return "arcal_dds::OpaquePayload";
}

template <> constexpr bool TopicTraits<::arcal_dds::OpaquePayload>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::arcal_dds::OpaquePayload>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::arcal_dds::OpaquePayload>::type_map_blob_sz() { return 214; }
template<> constexpr unsigned int TopicTraits<::arcal_dds::OpaquePayload>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::arcal_dds::OpaquePayload>::type_map_blob() {
  static const uint8_t blob[] = {
 0x40,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x32,  0x90,  0x88,  0x5a,  0x76,  0x8b,  0xe7, 
 0x5a,  0x89,  0xcc,  0x4d,  0x7c,  0x85,  0x28,  0x00,  0x28,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02, 
 0x8d,  0x77,  0x7f,  0x38,  0x67,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x9d,  0xec,  0x81, 
 0xa8,  0x76,  0xd9,  0xfb,  0x4a,  0xfe,  0x17,  0x37,  0xb7,  0xdc,  0x9d,  0x00,  0x4f,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x21,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x61,  0x72,  0x63,  0x61,  0x6c,  0x5f,  0x64,  0x64,  0x73,  0x3a,  0x3a,  0x4f,  0x70,  0x61,  0x71,  0x75, 
 0x65,  0x50,  0x61,  0x79,  0x6c,  0x6f,  0x61,  0x64,  0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x02,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x9d,  0xec,  0x81,  0xa8,  0x76,  0xd9,  0xfb, 
 0x4a,  0xfe,  0x17,  0x37,  0xb7,  0xdc,  0x9d,  0xf1,  0x32,  0x90,  0x88,  0x5a,  0x76,  0x8b,  0xe7,  0x5a, 
 0x89,  0xcc,  0x4d,  0x7c,  0x85,  0x28, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::arcal_dds::OpaquePayload>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x32,  0x90,  0x88,  0x5a,  0x76,  0x8b,  0xe7,  0x5a,  0x89,  0xcc,  0x4d, 
 0x7c,  0x85,  0x28,  0x00,  0x2c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x9d,  0xec,  0x81,  0xa8,  0x76,  0xd9,  0xfb,  0x4a,  0xfe,  0x17,  0x37, 
 0xb7,  0xdc,  0x9d,  0x00,  0x53,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::arcal_dds::OpaquePayload>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::arcal_dds::OpaquePayload>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::arcal_dds::OpaquePayload)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::arcal_dds::OpaquePayload>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::arcal_dds::OpaquePayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::arcal_dds::OpaquePayload& instance, bool as_key) {
  auto &props = get_type_props<::arcal_dds::OpaquePayload>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::arcal_dds::OpaquePayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!read(streamer, se_1))
        return false;
      instance.data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::arcal_dds::OpaquePayload& instance, bool as_key) {
  auto &props = get_type_props<::arcal_dds::OpaquePayload>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::arcal_dds::OpaquePayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::arcal_dds::OpaquePayload& instance, bool as_key) {
  auto &props = get_type_props<::arcal_dds::OpaquePayload>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::arcal_dds::OpaquePayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::arcal_dds::OpaquePayload& instance, bool as_key) {
  auto &props = get_type_props<::arcal_dds::OpaquePayload>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_ARCAL_PAYLOAD_HPP
