/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: arcal_payload.h
  Source: arcal_payload.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ARCAL_PAYLOAD_H
#define DDSC_ARCAL_PAYLOAD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct arcal_dds_OpaquePayload
{
  dds_sequence_octet data;
} arcal_dds_OpaquePayload;

extern const dds_topic_descriptor_t arcal_dds_OpaquePayload_desc;

#define arcal_dds_OpaquePayload__alloc() \
((arcal_dds_OpaquePayload*) dds_alloc (sizeof (arcal_dds_OpaquePayload)));

#define arcal_dds_OpaquePayload_free(d,o) \
dds_sample_free ((d), &arcal_dds_OpaquePayload_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ARCAL_PAYLOAD_H */
